<?xml version="1.0" encoding="utf-8"?><Database Name="TransportDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-LT\SQLEXPRESS;Initial Catalog=TransportDB;Persist Security Info=True;User ID=TransportApp;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="WpfApp.Properties.Settings" SettingsPropertyName="TransportDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Angajat" Member="Angajats">
    <Type Name="Angajat">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="salariu" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="id_persoana" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tip_angajat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data_angajarii" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="Angajat_MT" Member="MTs" ThisKey="id_unic" OtherKey="id_sofer" Type="MT" />
      <Association Name="Persoana_Angajat" Member="Persoana" ThisKey="id_persoana" OtherKey="id_unic" Type="Persoana" IsForeignKey="true" />
      <Association Name="Tip_Angajat_Angajat" Member="Tip_Angajat1" ThisKey="tip_angajat" OtherKey="id_unic" Type="Tip_Angajat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bilet" Member="Bilets">
    <Type Name="Bilet">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tip_bilet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="valabilitate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="id_calator" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nr_bilete" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tip_Bilet_Bilet" Member="Tip_Bilet1" ThisKey="tip_bilet" OtherKey="id_unic" Type="Tip_Bilet" IsForeignKey="true" />
      <Association Name="User_Bilet" Member="User" ThisKey="id_calator" OtherKey="id_unic" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Complaint" Member="Complaints">
    <Type Name="Complaint">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="text_plangere" Type="System.String" DbType="VarChar(1200)" CanBeNull="true" />
      <Column Name="id_tip_MTC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TipMT_Complaint" Member="TipMT" ThisKey="id_tip_MTC" OtherKey="id_unic" Type="TipMT" IsForeignKey="true" />
      <Association Name="User_Complaint" Member="User" ThisKey="id_user" OtherKey="id_unic" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Coordonate_Statie" Member="Coordonate_Staties">
    <Type Name="Coordonate_Statie">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_statie" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="coord_X" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="coord_Y" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tip_Statie_Coordonate_Statie" Member="Tip_Statie" ThisKey="id_statie" OtherKey="id_unic" Type="Tip_Statie" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MT" Member="MTs">
    <Type Name="MT">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_tip" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nr_traseu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nr_inmatriculare" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="id_sofer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numar_mt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Angajat_MT" Member="Angajat" ThisKey="id_sofer" OtherKey="id_unic" Type="Angajat" IsForeignKey="true" />
      <Association Name="TipMT_MT" Member="TipMT" ThisKey="id_tip" OtherKey="id_unic" Type="TipMT" IsForeignKey="true" />
      <Association Name="Traseu_MT" Member="Traseu" ThisKey="nr_traseu" OtherKey="id_unic" Type="Traseu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Persoana" Member="Persoanas">
    <Type Name="Persoana">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tip_persoana" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nume" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="prenume" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CNP" Type="System.String" DbType="Char(13)" CanBeNull="true" />
      <Column Name="adresa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Persoana_Angajat" Member="Angajats" ThisKey="id_unic" OtherKey="id_persoana" Type="Angajat" />
      <Association Name="Persoana_User" Member="Users" ThisKey="id_unic" OtherKey="id_persoana" Type="User" />
      <Association Name="Tip_User_Persoana" Member="Tip_User" ThisKey="tip_persoana" OtherKey="id_unic" Type="Tip_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Statie" Member="Staties">
    <Type Name="Statie">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_traseu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_tip_statie" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ore" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Tip_Statie_Statie" Member="Tip_Statie" ThisKey="id_tip_statie" OtherKey="id_unic" Type="Tip_Statie" IsForeignKey="true" />
      <Association Name="Traseu_Statie" Member="Traseu" ThisKey="id_traseu" OtherKey="id_unic" Type="Traseu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tip_Angajat" Member="Tip_Angajats">
    <Type Name="Tip_Angajat">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nume" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Tip_Angajat_Angajat" Member="Angajats" ThisKey="id_unic" OtherKey="tip_angajat" Type="Angajat" />
    </Type>
  </Table>
  <Table Name="dbo.Tip_Bilet" Member="Tip_Bilets">
    <Type Name="Tip_Bilet">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nume" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Tip_Bilet_Bilet" Member="Bilets" ThisKey="id_unic" OtherKey="tip_bilet" Type="Bilet" />
    </Type>
  </Table>
  <Table Name="dbo.Tip_Statie" Member="Tip_Staties">
    <Type Name="Tip_Statie">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nume" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Tip_Statie_Coordonate_Statie" Member="Coordonate_Staties" ThisKey="id_unic" OtherKey="id_statie" Type="Coordonate_Statie" />
      <Association Name="Tip_Statie_Statie" Member="Staties" ThisKey="id_unic" OtherKey="id_tip_statie" Type="Statie" />
    </Type>
  </Table>
  <Table Name="dbo.Tip_User" Member="Tip_Users">
    <Type Name="Tip_User">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nume" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Tip_User_Persoana" Member="Persoanas" ThisKey="id_unic" OtherKey="tip_persoana" Type="Persoana" />
    </Type>
  </Table>
  <Table Name="dbo.TipMT" Member="TipMTs">
    <Type Name="TipMT">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nume" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="TipMT_Complaint" Member="Complaints" ThisKey="id_unic" OtherKey="id_tip_MTC" Type="Complaint" />
      <Association Name="TipMT_MT" Member="MTs" ThisKey="id_unic" OtherKey="id_tip" Type="MT" />
    </Type>
  </Table>
  <Table Name="dbo.Traseu" Member="Traseus">
    <Type Name="Traseu">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nume" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Traseu_MT" Member="MTs" ThisKey="id_unic" OtherKey="nr_traseu" Type="MT" />
      <Association Name="Traseu_Statie" Member="Staties" ThisKey="id_unic" OtherKey="id_traseu" Type="Statie" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="id_unic" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="id_persoana" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Bilet" Member="Bilets" ThisKey="id_unic" OtherKey="id_calator" Type="Bilet" />
      <Association Name="User_Complaint" Member="Complaints" ThisKey="id_unic" OtherKey="id_user" Type="Complaint" />
      <Association Name="Persoana_User" Member="Persoana" ThisKey="id_persoana" OtherKey="id_unic" Type="Persoana" IsForeignKey="true" />
    </Type>
  </Table>
</Database>